from langchain_community.document_loaders import WebBaseLoader

# Loading all the webpages of TVS Credit website

urls = [
    'https://www.tvscredit.com/',
    'https://www.tvscredit.com/dealer-locator',
    'https://www.tvscredit.com/loans/business-loans',
    'https://www.tvscredit.com/loans/online-personal-loans/',
    'https://www.tvscredit.com/loans/consumer-durable-loans',
    'https://www.tvscredit.com/blog',
    'https://www.tvscredit.com/loans/business-loans/loan-against-machinery',
    'https://www.tvscredit.com/loans/instacard/',
    'https://www.tvscredit.com/investors',
    'https://www.tvscredit.com/sitemap',
    'https://www.tvscredit.com/loans/two-wheeler-loans',
    'https://www.tvscredit.com/loans/tractor-loans',
    'https://www.tvscredit.com/loans/business-loans/retail-business-loans',
    'https://www.tvscredit.com/loans/business-loans/emerging-and-mid-corporate-business-loans',
    'https://www.tvscredit.com/loans/online-personal-loans/',
    'https://www.tvscredit.com/loans/business-loans/balance-transfer',
    'https://www.tvscredit.com/loans/business-loans/working-capital-loan',
    'https://www.tvscredit.com/loans/business-loans/unsecured-business-loans',
    'https://www.tvscredit.com/loans/used-commercial-vehicle-loans',
    'https://www.tvscredit.com/loans/used-car-loans',
    'https://www.tvscredit.com/investors/code-of-business-conduct-and-ethics',
    'https://www.tvscredit.com/loans/business-loans/loan-against-property',
    'https://www.tvscredit.com/get-in-touch',
    'https://www.tvscredit.com/about-us',
    'https://www.tvscredit.com/careers/current-opening',
    'https://www.tvscredit.com/careers',
    'https://www.tvscredit.com/apply-for-loan-online',
    'https://www.tvscredit.com/loans/three-wheeler-loans',
    'https://www.tvscredit.com/privacy-policy',
    'https://www.tvscredit.com/terms-and-conditions',
    'https://www.tvscredit.com/investors/rbi-compliance',
    'https://www.tvscredit.com/investors/investor-information',
    'https://www.tvscredit.com/blog/consumer-durable-loans/top-5-things-to-consider-before-going-for-a-consumer-durable-loan',
    'https://www.tvscredit.com/blog/consumer-durable-loans/fantastic-4-tips-to-improve-your-cibil-score-immediately',
    'https://www.tvscredit.com/blog/consumer-durable-loans/consumer-durable-loans-adding-luxury-to-life',
    'https://www.tvscredit.com/blog/used-car-loans/4-step-guide-to-buy-a-used-car-in-india',
    'https://www.tvscredit.com/blog/two-wheeler-loans/a-guide-to-choosing-the-right-two-wheeler-loan',
    'https://www.tvscredit.com/blog/business-loans/how-to-overcome-cash-crisis-grow-your-small-business',
    'https://www.tvscredit.com/blog/business-loans/machinery-loans-improving-productivity-through-innovation',
    'https://www.tvscredit.com/blog/general/are-these-4-popular-myths-stopping-you-taking-a-loan-youll-be-surprised',
    'https://www.tvscredit.com/blog/general/my-internship-with-tvs-credit-services-magaan',
    'https://www.tvscredit.com/blog/general/tvs-credit-saathi-app',
    'https://www.tvscredit.com/blog/two-wheeler-loans/apply-for-a-tvs-credit-two-wheeler-loan-with-a-few-simple-steps',
    'https://www.tvscredit.com/blog/general/how-to-avoid-fraudulent-transactions',
    'https://www.tvscredit.com/blog/general/my-summer-internship-at-tvs-credit-pavithra-pradeep',
    'https://www.tvscredit.com/blog/tractor-loans/top-4-things-you-must-do-before-approaching-a-lender-for-a-farm-loan',
    'https://www.tvscredit.com/blog/tractor-loans/top-9-tips-to-maintain-a-tractor',
    'https://www.tvscredit.com/blog/three-wheeler-loans/tips-to-run-an-auto-rickshaw-business-efficiently',
    'https://www.tvscredit.com/blog/business-loans/why-take-a-balance-transfer-loan-on-your-existing-business-loan',
    'https://www.tvscredit.com/blog/general/19-skills-you-need-to-be-successful-in-2019',
    'https://www.tvscredit.com/blog/general/my-virtual-summer-internship-at-tvs-credit-was-a-once-in-a-lifetime-experience-shubham-langer',
    'https://www.tvscredit.com/blog/three-wheeler-loans/top-4-maintenance-tips-to-keep-your-three-wheeler-in-top-condition',
    'https://www.tvscredit.com/blog/used-car-loans/buying-a-used-car-on-a-loan-here-are-6-things-you-must-know',
    'https://www.tvscredit.com/blog/general/a-virtual-summer-internship-journey-with-tvs-credit-paul-p-vinod-scmhrd-pune',
    'https://www.tvscredit.com/blog/used-commercial-vehicle-loans/used-commercial-vehicle-what-lies-ahead',
    'https://www.tvscredit.com/blog/two-wheeler-loans/ride-your-dream-machine-and-do-more-in-life',
    'https://www.tvscredit.com/blog/general/saksham',
    'https://www.tvscredit.com/blog/general/an-internship-in-the-time-of-covid-19-by-akansha-gupta-k-j-somaiya-institute-of-management-2020',
    'https://www.tvscredit.com/blog/general/make-online-payment-of-your-tvs-credit-loan-emis-safely-quickly-and-conveniently',
    'https://www.tvscredit.com/blog/two-wheeler-loans/tvs-credit-two-wheeler-loans-features-and-benefits-for-better-and-flexible-everyday-commute',
    'https://www.tvscredit.com/blog/general/my-exciting-journey-with-tvs-credit-yusuf-merchant',
    'https://www.tvscredit.com/about-us/know-the-brand',
    'https://www.tvscredit.com/blog/consumer-durable-loans',
    'https://www.tvscredit.com/blog/used-commercial-vehicle-loans',
    'https://www.tvscredit.com/blog/three-wheeler-loans',
    'https://www.tvscredit.com/blog/tractor-loans',
    'https://www.tvscredit.com/blog/general',
    'https://www.tvscredit.com/blog/business-loans',
    'https://www.tvscredit.com/blog/two-wheeler-loans',
    'https://www.tvscredit.com/blog/used-car-loans'
]


def get_web_documents():
    loader = WebBaseLoader(urls)
    docs = loader.load()
    return docs